spring:
  profiles: eureka1
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
---
spring:
  profiles: eureka2
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
